       <tr>
         <td>{{owner}}</td>
         <td>{{name}}</td>
         <td>{{type}}</td>
         <td>{{ellapsed}}</td>
         <td class="d-flex justify-content-center">
           <div class="btn-group">
             <a href="/connect/{{id}}/" class="btn btn-sm btn-outline-secondary">Connect</a>
             <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#stopWorkspace" data-id="{{id}}" data-name="{{name}}">Stop</button>
           </div>
         </td>
       </tr>
