	<div class="col-md-4">
	  <div class="card mb-4 box-shadow">
	    <img class="card-img-top" src="/images/{{id}}.png" alt="{{description}}"/>
	    <div class="card-body">
	      <p class="card-text">{{description}}</p>
	      <div class="d-flex justify-content-center">
	        <button type="button" class="btn btn-sm btn-outline-secondary start-button" data-toggle="modal" data-target="#startWorkspace" data-id="{{id}}" data-title="{{title}}">Create {{title}}</button>
	      </div>
	    </div>
	  </div>
	</div>
